-- V1: baseline schema
-- All four tables. Flyway runs this exactly once and records it in flyway_schema_history.
-- A "good" Flyway migration is: small, named after what it does, and NEVER edited after commit.

-- Postgres type notes:
--   BIGINT GENERATED BY DEFAULT AS IDENTITY → native auto-incrementing key, matches Java Long
--   BOOLEAN                             → native true/false, matches Java boolean directly
--   DATE / TIMESTAMPTZ                  → native date/instant types, match LocalDate / Instant directly

CREATE TABLE categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT    NOT NULL,
    type          TEXT    NOT NULL,          -- 'INCOME' or 'EXPENSE'
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL
);

CREATE TABLE subcategories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT    NOT NULL,
    category_id   BIGINT  NOT NULL REFERENCES categories(id),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL
);

-- 'transaction' is a reserved SQL keyword in many databases, so we use 'transactions'
CREATE TABLE transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           DATE        NOT NULL,
    amount         NUMERIC     NOT NULL,        -- BigDecimal, always stored with scale=2
    description    TEXT        CHECK (length(description) <= 255),
    subcategory_id BIGINT      NOT NULL REFERENCES subcategories(id),
    created_at     TIMESTAMPTZ NOT NULL,        -- Instant, stored as UTC
    updated_at     TIMESTAMPTZ NOT NULL,
    deleted        BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE TABLE monthly_budgets (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year             INTEGER NOT NULL,
    month            INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    subcategory_id   BIGINT  NOT NULL REFERENCES subcategories(id),
    projected_amount NUMERIC NOT NULL,
    UNIQUE (year, month, subcategory_id)
);
